[phases.setup]
nixPkgs = ['python39', 'nodejs']  # Use Python 3.9 for Streamlit 1.45.1 compatibility
aptPkgs = ['python3-pip', 'build-essential', 'libpq-dev', 'libjpeg-dev', 'zlib1g-dev', 'libpng-dev', 'libfreetype6-dev', 'libopenjp2-7-dev']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'streamlit run main.py --server.port 8501 --server.headless true'
